// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUnjI-mTAmzfcQDMiaMAyD8zNpppAZ_W4',
    appId: '1:296985830122:web:7d6e2e0ec9608420d9ad93',
    messagingSenderId: '296985830122',
    projectId: 'pantry-recipeapp',
    authDomain: 'pantry-recipeapp.firebaseapp.com',
    storageBucket: 'pantry-recipeapp.appspot.com',
    measurementId: 'G-NTWC72FQWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHGI_6SpwpFEECg_Yeh-FCuqqVU36sFbY',
    appId: '1:296985830122:android:ba6b9baa3dacc4b2d9ad93',
    messagingSenderId: '296985830122',
    projectId: 'pantry-recipeapp',
    storageBucket: 'pantry-recipeapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADWdvnwnz2oglUTiC2rUlyoafLFgsIBOA',
    appId: '1:296985830122:ios:8e4cd5cafb344b2ad9ad93',
    messagingSenderId: '296985830122',
    projectId: 'pantry-recipeapp',
    storageBucket: 'pantry-recipeapp.appspot.com',
    iosClientId: '296985830122-8oj4bvju2o5u3heesmap2o9oqk6lrdm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADWdvnwnz2oglUTiC2rUlyoafLFgsIBOA',
    appId: '1:296985830122:ios:8e4cd5cafb344b2ad9ad93',
    messagingSenderId: '296985830122',
    projectId: 'pantry-recipeapp',
    storageBucket: 'pantry-recipeapp.appspot.com',
    iosClientId: '296985830122-8oj4bvju2o5u3heesmap2o9oqk6lrdm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantry',
  );
}
